### ISSUE TITLE
Volumes for nginx container can be mounted from the environment file

### ISSUE THREAD

**Issue by kneerunjun** [eensymachines-in/luminapi#27]
```yml
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes: 
      # for local development the volume mapping changes
      # - "/home/niranjan/repos/eensymachines.in/luminapi/nginx/luminapp:/var/www/luminapp"
      - "/root/repos/eensymachines.in/luminapi/nginx/luminapp:/var/www/luminapp"
```
Its counter productive to change the volume definition everytime. need to pick this from environment file
